name: Github to Aws codecommit
description: "sync from github"
author: "mersch"
branding:
  icon: terminal
  color:  yellow
inputs:
  repository_name:
    description: Codecommit repository name
    required: true
  aws_region:
    description: Region of codecommit
    required: true

runs:
  using: "docker"
  image: "./Dockerfile"